ALTER TABLE article_tests
ADD COLUMN IF NOT EXISTS report_generated BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS report_url TEXT,
ADD COLUMN IF NOT EXISTS report_generated_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS report_number VARCHAR(255);

ALTER TABLE order_tests
ADD COLUMN IF NOT EXISTS report_generated BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS report_url TEXT,
ADD COLUMN IF NOT EXISTS report_generated_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS report_number VARCHAR(255);

CREATE TABLE IF NOT EXISTS report_sequence (
  id SERIAL PRIMARY KEY,
  year INTEGER UNIQUE NOT NULL,
  last_sequence_number INTEGER NOT NULL DEFAULT 0
);
